In [1]:
import pandas as pd

In [9]:
import os 

folder = r"E:\Power BI project for ANUDIP"

print(os.path.exists(folder))

True

In [10]:
print(os.listdir(r"E:\Power BI project for ANUDIP"))

['food_delivery_data_dictionary.csv', 'food_delivery_master.csv']

In [13]:

df=pd.read_csv(r"E:\Power BI project for ANUDIP\food_delivery_master.csv")
df.head()

,order_id,order_timestamp,order_date,order_hour,day_of_week,is_weekend,day_type,peak_hour,customer_id,customer_age,...,is_cancelled,cancellation_reason,subtotal,discount_percent,tax_amount,service_fee,delivery_fee,order_total,tip_amount,payment_method
0,ORD_003324,2025-10-01 00:45:00,2025-10-01,0,Wednesday,0,Weekday,0,CUS_00017,29,...,0,Not Cancelled,48.17,0,6.74,2.44,3.50,60.85,0.00,Cash
1,ORD_006549,2025-10-01 00:46:00,2025-10-01,0,Wednesday,0,Weekday,0,CUS_00824,20,...,0,Not Cancelled,53.05,5,7.06,1.84,4.35,63.65,0.00,Cash
2,ORD_020895,2025-10-01 00:15:00,2025-10-01,0,Wednesday,0,Weekday,0,CUS_00328,29,...,0,Not Cancelled,9.35,15,1.11,0.29,3.00,12.35,1.03,Digital Wallet
3,ORD_020927,2025-10-01 00:41:00,2025-10-01,0,Wednesday,0,Weekday,0,CUS_01053,36,...,0,Not Cancelled,19.49,0,2.73,1.12,4.65,27.99,0.00,Credit Card
4,ORD_022639,2025-10-01 00:37:00,2025-10-01,0,Wednesday,0,Weekday,0,CUS_00004,19,...,0,Not Cancelled,57.03,15,6.79,2.36,6.70,64.33,0.00,Cash

In [15]:
df.shape

(50000, 42)

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 42 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   order_id                         50000 non-null  object
 1   order_timestamp                  50000 non-null  object
 2   order_date                       50000 non-null  object
 3   order_hour                       50000 non-null  int64
 4   day_of_week                      50000 non-null  object
 5   is_weekend                       50000 non-null  int64
 6   day_type                         50000 non-null  object
 7   peak_hour                        50000 non-null  int64
 8   customer_id                      50000 non-null  object
 9   customer_age                     50000 non-null  int64
 10  customer_type                    50000 non-null  object
 11  customer_rating                  49132 non-null  float64
 12  restaurant_id                    50000 non-null  object
 13  restaurant_type                  50000 non-null  object
 14  restaurant_category              50000 non-null  object
 15  restaurant_rating                50000 non-null  float64
 16  restaurant_preparation_time_min  50000 non-null  int64
 17  items_count                      50000 non-null  int64
 18  driver_id                        50000 non-null  object
 19  driver_experience_months         50000 non-null  int64
 20  driver_rating                    50000 non-null  float64
 21  city                             50000 non-null  object
 22  delivery_area                    50000 non-null  object
 23  distance_km                      50000 non-null  float64
 24  weather                          50000 non-null  object
 25  traffic_level                    50000 non-null  object
 26  estimated_delivery_time_min      50000 non-null  int64
 27  actual_delivery_time_min         49132 non-null  float64
 28  delivery_delay_min               49132 non-null  float64
 29  late_delivery                    49132 non-null  float64
 30  delay_category                   50000 non-null  object
 31  order_status                     50000 non-null  object
 32  is_cancelled                     50000 non-null  int64
 33  cancellation_reason              50000 non-null  object
 34  subtotal                         50000 non-null  float64
 35  discount_percent                 50000 non-null  int64
 36  tax_amount                       50000 non-null  float64
 37  service_fee                      50000 non-null  float64
 38  delivery_fee                     50000 non-null  float64
 39  order_total                      50000 non-null  float64
 40  tip_amount                       49132 non-null  float64
 41  payment_method                   50000 non-null  object
dtypes: float64(13), int64(10), object(19)
memory usage: 16.0+ MB

In [26]:
df.isnull().sum()

order_id                             0
order_timestamp                      0
order_date                           0
order_hour                           0
day_of_week                          0
is_weekend                           0
day_type                             0
peak_hour                            0
customer_id                          0
customer_age                         0
customer_type                        0
customer_rating                    868
restaurant_id                        0
restaurant_type                      0
restaurant_category                  0
restaurant_rating                    0
restaurant_preparation_time_min      0
items_count                          0
driver_id                            0
driver_experience_months             0
driver_rating                        0
city                                 0
delivery_area                        0
distance_km                          0
weather                              0
traffic_level                        0
estimated_delivery_time_min          0
actual_delivery_time_min           868
delivery_delay_min                 868
late_delivery                      868
delay_category                       0
order_status                         0
is_cancelled                         0
cancellation_reason                  0
subtotal                             0
discount_percent                     0
tax_amount                           0
service_fee                          0
delivery_fee                         0
order_total                          0
tip_amount                         868
payment_method                       0
dtype: int64

In [27]:
missing_percentage = (df.isnull().sum() / len(df)) * 100
missing_percentage.sort_values(ascending=False)

late_delivery                      1.736
customer_rating                    1.736
actual_delivery_time_min           1.736
delivery_delay_min                 1.736
tip_amount                         1.736
day_of_week                        0.000
order_date                         0.000
order_hour                         0.000
order_id                           0.000
order_timestamp                    0.000
customer_age                       0.000
customer_id                        0.000
peak_hour                          0.000
day_type                           0.000
is_weekend                         0.000
customer_type                      0.000
restaurant_id                      0.000
restaurant_type                    0.000
driver_id                          0.000
driver_experience_months           0.000
driver_rating                      0.000
city                               0.000
restaurant_category                0.000
restaurant_rating                  0.000
restaurant_preparation_time_min    0.000
items_count                        0.000
traffic_level                      0.000
weather                            0.000
distance_km                        0.000
delivery_area                      0.000
delay_category                     0.000
order_status                       0.000
is_cancelled                       0.000
estimated_delivery_time_min        0.000
cancellation_reason                0.000
subtotal                           0.000
tax_amount                         0.000
discount_percent                   0.000
service_fee                        0.000
delivery_fee                       0.000
order_total                        0.000
payment_method                     0.000
dtype: float64

In [20]:
df.duplicated().sum()

np.int64(0)

In [21]:
df.describe()

,order_hour,is_weekend,peak_hour,customer_age,customer_rating,restaurant_rating,restaurant_preparation_time_min,items_count,driver_experience_months,driver_rating,...,delivery_delay_min,late_delivery,is_cancelled,subtotal,discount_percent,tax_amount,service_fee,delivery_fee,order_total,tip_amount
count,50000.000000,50000.00000,50000.00000,50000.000000,49132.000000,50000.000000,50000.000000,50000.00000,50000.0000,50000.000000,...,49132.000000,49132.000000,50000.00000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,49132.000000
mean,14.465900,0.26712,0.61664,27.686580,4.295946,4.207956,15.549600,2.91002,29.7332,4.495062,...,4.232822,0.365709,0.01736,30.897938,4.495700,4.128796,1.474600,3.075108,38.169501,1.610076
std,5.231155,0.44246,0.48621,7.537796,0.530947,0.450977,7.360099,2.02907,17.4052,0.349198,...,5.488314,0.481633,0.13061,27.068965,6.430008,3.636275,1.378101,2.299115,31.054669,2.878464
min,0.000000,0.00000,0.00000,18.000000,1.800000,2.800000,5.000000,1.00000,1.0000,3.200000,...,-12.000000,0.000000,0.00000,5.100000,0.000000,0.570000,0.130000,0.000000,4.870000,0.000000
25%,11.000000,0.00000,0.00000,21.000000,4.000000,3.900000,10.000000,1.00000,14.0000,4.300000,...,1.000000,0.000000,0.00000,13.100000,0.000000,1.730000,0.580000,0.000000,17.430000,0.000000
50%,14.000000,0.00000,1.00000,27.000000,4.400000,4.200000,14.000000,2.00000,29.0000,4.500000,...,4.000000,0.000000,0.00000,22.825000,0.000000,2.890000,1.040000,3.500000,28.350000,0.000000
75%,19.000000,1.00000,1.00000,33.000000,4.700000,4.600000,19.000000,4.00000,44.0000,4.800000,...,7.000000,1.000000,0.00000,40.120000,10.000000,5.390000,1.890000,4.500000,48.660000,2.280000
max,23.000000,1.00000,1.00000,55.000000,5.000000,5.000000,73.000000,10.00000,60.0000,5.000000,...,75.000000,1.000000,1.00000,362.980000,20.000000,50.820000,25.210000,12.000000,443.210000,53.650000

In [23]:
df.columns

Index(['order_id', 'order_timestamp', 'order_date', 'order_hour',
       'day_of_week', 'is_weekend', 'day_type', 'peak_hour', 'customer_id',
       'customer_age', 'customer_type', 'customer_rating', 'restaurant_id',
       'restaurant_type', 'restaurant_category', 'restaurant_rating',
       'restaurant_preparation_time_min', 'items_count', 'driver_id',
       'driver_experience_months', 'driver_rating', 'city', 'delivery_area',
       'distance_km', 'weather', 'traffic_level',
       'estimated_delivery_time_min', 'actual_delivery_time_min',
       'delivery_delay_min', 'late_delivery', 'delay_category', 'order_status',
       'is_cancelled', 'cancellation_reason', 'subtotal', 'discount_percent',
       'tax_amount', 'service_fee', 'delivery_fee', 'order_total',
       'tip_amount', 'payment_method'],
      dtype='object')

In [24]:
df.nunique()

order_id                           50000
order_timestamp                    25459
order_date                            30
order_hour                            24
day_of_week                            7
is_weekend                             2
day_type                               2
peak_hour                              2
customer_id                         4979
customer_age                          37
customer_type                          3
customer_rating                       33
restaurant_id                        250
restaurant_type                        4
restaurant_category                    6
restaurant_rating                     21
restaurant_preparation_time_min       67
items_count                           10
driver_id                            200
driver_experience_months              55
driver_rating                         15
city                                   4
delivery_area                         40
distance_km                          192
weather                                4
traffic_level                          3
estimated_delivery_time_min          110
actual_delivery_time_min             131
delivery_delay_min                    68
late_delivery                          2
delay_category                         5
order_status                           2
is_cancelled                           2
cancellation_reason                    6
subtotal                            8930
discount_percent                       5
tax_amount                          2034
service_fee                          962
delivery_fee                         191
order_total                        10333
tip_amount                          1606
payment_method                         3
dtype: int64